name: Rust

on:
    pull_request:
        types:
            - opened
            - reopened
    push:

jobs:
    pwa-api:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./pwa-api
        steps:
            - name: Checkout Crate
              uses: actions/checkout@v4
            - name: Set Toolchain
              uses: dtolnay/rust-toolchain@stable
            - name: cargo check
              run: cargo check
            - name: cargo clippy
              run: cargo clippy

    sensor-api:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./sensor-api
        steps:
            - name: Checkout Crate
              uses: actions/checkout@v4
            - name: Set Toolchain
              uses: dtolnay/rust-toolchain@stable
            - name: cargo check
              run: cargo check
            - name: cargo clippy
              run: cargo clippy
